// react/src/components/controllers/PremieresController.tsx
// Converted from src/sections/premieres/premieres.ctrl.js

import React, { useEffect, useState } from 'react';
import { useLocation } from 'react-router-dom';
import Show from '../directives/show';
import PageValues from '../../services/page.val';

interface Show {
  id: number;
}

interface PremieresControllerProps {
  shows: Show[];
}

const PremieresController: React.FC<PremieresControllerProps> = ({ shows }) => {
  const [pageTitle, setPageTitle] = useState<string>('');
  const [pageDescription, setPageDescription] = useState<string>('');
  const location = useLocation();

  useEffect(() => {
    // Set page title and description
    setPageTitle("PREMIERES");
    setPageDescription("Brand new shows showing this month.");
    PageValues.title = pageTitle;
    PageValues.description = pageDescription;
  }, [pageTitle, pageDescription]);

  return (
    <div>
      <h1>{pageTitle}</h1>
      <p>{pageDescription}</p>
      <div>
        {shows.map(show => (
          <Show key={show.id} show={show} />
        ))}
      </div>
    </div>
  );
};

export default PremieresController;

// angular/src/app/components/PremieresController/PremieresController.component.ts
// Converted from src/sections/premieres/premieres.ctrl.js

import { Component, OnInit } from '@angular/core';
import { ShowService } from '../../services/show.service';
import { PageValuesService } from '../../services/page-values.service';

@Component({
  selector: 'app-premieres',
  templateUrl: './premieres.component.html',
  styleUrls: ['./premieres.component.css']
})
export class PremieresComponent implements OnInit {
  shows: any[] = [];

  constructor(private showService: ShowService, private pageValues: PageValuesService) {}

  ngOnInit(): void {
    this.pageValues.title = "PREMIERES";
    this.pageValues.description = "Brand new shows showing this month.";
    this.loadShows();
  }

  private loadShows(): void {
    this.showService.getPremieres().then(shows => {
      this.shows = shows;
    });
  }
}
