// angular/src/app/components/ViewController/ViewController.component.ts
// Converted from src/sections/view/view.ctrl.js

import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { ShowService } from '../../services/show.service';
import { PageValuesService } from '../../services/page-values.service';

@Component({
  selector: 'app-view-controller',
  templateUrl: './ViewController.component.html',
  styleUrls: ['./ViewController.component.css']
})
export class ViewControllerComponent implements OnInit {
  show: any = {};
  cast: any[] = [];

  constructor(
    private route: ActivatedRoute,
    private showService: ShowService,
    private pageValues: PageValuesService
  ) {}

  ngOnInit(): void {
    const showId = this.route.snapshot.paramMap.get('id');
    if (showId) {
      this.showService.get(showId).subscribe(show => {
        this.show = show;
        this.pageValues.title = "VIEW";
        this.pageValues.description = `Overview, seasons & info for '${show.original_name}'.`;
        this.loadCast(showId);
      });
    }
  }

  setBannerImage(): { [key: string]: string } {
    return {
      'background': 'url() no-repeat',
      'background-size': '100%',
      'background-position': '100% 0%'
    };
  }

  private loadCast(showId: string): void {
    this.showService.getCast(showId).subscribe(response => {
      this.cast = response.cast;
    });
  }
}

// react/src/components/controllers/ViewController.tsx
﻿// Converted from src/sections/view/view.ctrl.js

import React, { useEffect, useState } from 'react';
import { useParams } from 'react-router-dom';
import ShowService from '../../services/showService';
import PageValues from '../../utils/constants/PageValues';

type Show = {
    id: number;
    original_name: string;
    cast: Array<{ name: string }>;
};

const ViewController: React.FC = () => {
    const { id } = useParams<{ id: string }>();
    const [show, setShow] = useState<Show | null>(null);

    useEffect(() => {
        if (id) {
            ShowService.get(id).then((data) => {
                setShow(data);
                PageValues.title = "VIEW";
                PageValues.description = `Overview, seasons & info for '${data.original_name}'.`;
            });

            ShowService.getCast(id).then((response) => {
                if (show) {
                    setShow({ ...show, cast: response.cast });
                }
            });
        }
    }, [id]);

    const setBannerImage = () => ({
        background: 'url() no-repeat',
        backgroundSize: '100%',
        backgroundPosition: '100% 0%',
    });

    if (!show) return null;

    return (
        <div style={setBannerImage()}>
            <h1>{show.original_name}</h1>
            <ul>
                {show.cast.map((member, index) => (
                    <li key={index}>{member.name}</li>
                ))}
            </ul>
        </div>
    );
};

export default ViewController;
