// angular/src/app/components/ViewController.component.ts
// Converted from src/sections/view/view.ctrl.js

import { Component, Input, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { ShowService } from '../services/ShowService.service';
import { PageValues } from '../constants/PageValues';

@Component({
  selector: 'app-view-controller',
  templateUrl: './view.tpl.html',
  styleUrls: ['./view.css']
})
export class ViewControllerComponent implements OnInit {
  @Input() show!: any;

  constructor(
    private showService: ShowService,
    private route: ActivatedRoute,
    private pageValues: PageValues
  ) {}

  ngOnInit(): void {
    this.pageValues.title = "VIEW";
    this.pageValues.description = `Overview, seasons & info for '${this.show.original_name}'.`;

    this.show.cast = [];
    this.showService.getCast(this.show.id).then(response => {
      this.show.cast = response.cast;
    });
  }

  setBannerImage() {
    return {
      'background': 'url() no-repeat',
      'background-size': '100%',
      'background-position': '100% 0%'
    };
  }
}

// react/src/components/controllers/ViewController.tsx
﻿// Converted from src/sections/view/view.ctrl.js

import React, { useEffect, useState } from 'react';
import { useParams } from 'react-router-dom';
import ShowService from '../../services/showService';
import PageValues from '../../utils/constants/PageValues';

type Show = {
    id: number;
    original_name: string;
    cast: Array<{ name: string }>;
};

const ViewController: React.FC = () => {
    const { id } = useParams<{ id: string }>();
    const [show, setShow] = useState<Show | null>(null);

    useEffect(() => {
        if (id) {
            ShowService.get(id).then((data) => {
                setShow(data);
                PageValues.title = "VIEW";
                PageValues.description = `Overview, seasons & info for '${data.original_name}'.`;
            });

            ShowService.getCast(id).then((response) => {
                if (show) {
                    setShow({ ...show, cast: response.cast });
                }
            });
        }
    }, [id]);

    const setBannerImage = () => ({
        background: 'url() no-repeat',
        backgroundSize: '100%',
        backgroundPosition: '100% 0%',
    });

    if (!show) return null;

    return (
        <div style={setBannerImage()}>
            <h1>{show.original_name}</h1>
            <ul>
                {show.cast.map((member, index) => (
                    <li key={index}>{member.name}</li>
                ))}
            </ul>
        </div>
    );
};

export default ViewController;
