// angular/src/app/components/PopularController/PopularController.component.ts
// Converted from src/sections/popular/popular.ctrl.js

import { Component, OnInit } from '@angular/core';
import { ShowService } from '../../services/show.service';
import { PageValuesService } from '../../services/page-values.service';

@Component({
  selector: 'app-popular',
  templateUrl: './popular.component.html',
  styleUrls: ['./popular.component.css']
})
export class PopularComponent implements OnInit {
  shows: any[] = [];

  constructor(private showService: ShowService, private pageValues: PageValuesService) {}

  ngOnInit(): void {
    this.pageValues.title = "POPULAR";
    this.pageValues.description = "The most popular TV shows.";
    this.loadShows();
  }

  private loadShows(): void {
    this.showService.getPopular().then(shows => {
      this.shows = shows;
    });
  }
}

// react/src/components/PopularController.tsx
﻿// Converted from src/sections/popular/popular.ctrl.js

import React, { useEffect, useState } from 'react';
import PageValues from '../utils/constants/PageValues'; // Corrected the import path

type ShowType = {
    id: number;
    name: string;
};

const PopularController: React.FC<{ shows: ShowType[] }> = ({ shows }) => {
    const [popularShows, setPopularShows] = useState<ShowType[]>([]);

    useEffect(() => {
        // Set page title and description
        PageValues.title = "POPULAR";
        PageValues.description = "The most popular TV shows.";

        // Setup view model object
        setPopularShows(shows);
    }, [shows]);

    return (
        <div>
            <h1>Popular Shows</h1>
            <ul>
                {popularShows.map((show) => (
                    <li key={show.id}>{show.name}</li>
                ))}
            </ul>
        </div>
    );
};

export default PopularController;
