// angular/src/app/components/PopularController.component.ts
// Converted from src/sections/popular/popular.ctrl.js

import { Component, Input, OnInit } from '@angular/core';
import { PageValues } from '../constants/PageValues';

@Component({
  selector: 'app-popular-controller',
  templateUrl: './popular.tpl.html',
  styleUrls: ['./popular.css']
})
export class PopularControllerComponent implements OnInit {
  @Input() shows!: any[];

  constructor(private pageValues: PageValues) {}

  ngOnInit(): void {
    // Set page title and description
    this.pageValues.title = "POPULAR";
    this.pageValues.description = "The most popular TV shows.";
  }
}

// react/src/components/PopularController.tsx
﻿// Converted from src/sections/popular/popular.ctrl.js

import React, { useEffect, useState } from 'react';
import PageValues from '../utils/constants/PageValues'; // Corrected the import path

type ShowType = {
    id: number;
    name: string;
};

const PopularController: React.FC<{ shows: ShowType[] }> = ({ shows }) => {
    const [popularShows, setPopularShows] = useState<ShowType[]>([]);

    useEffect(() => {
        // Set page title and description
        PageValues.title = "POPULAR";
        PageValues.description = "The most popular TV shows.";

        // Setup view model object
        setPopularShows(shows);
    }, [shows]);

    return (
        <div>
            <h1>Popular Shows</h1>
            <ul>
                {popularShows.map((show) => (
                    <li key={show.id}>{show.name}</li>
                ))}
            </ul>
        </div>
    );
};

export default PopularController;
