// angular/src/app/components/PremieresController.component.ts
// Converted from src/sections/premieres/premieres.ctrl.js

import { Component, Input } from '@angular/core';
import { PageValuesService } from '../constants/PageValues';
import { ShowService } from '../services/ShowService.service';

@Component({
  selector: 'app-premieres-controller',
  templateUrl: './premieres-controller.component.html',
  styleUrls: ['./premieres-controller.component.css']
})
export class PremieresControllerComponent {
  @Input() shows!: any[];

  constructor(private pageValues: PageValuesService, private showService: ShowService) {
    // Set page title and description
    this.pageValues.title = "PREMIERES";
    this.pageValues.description = "Brand new shows showing this month.";

    // Initialize shows
    this.showService.getPremieres().then(shows => {
      this.shows = shows;
    });
  }
}

// react/src/components/PremieresController.tsx
﻿// Converted from src/sections/premieres/premieres.ctrl.js

import React, { useState, useEffect } from 'react';
import PageValues from '../utils/constants/PageValues';

type ShowType = {
    // Define the structure of a show object if known
};

type PremieresControllerProps = {
    shows: ShowType[];
};

const PremieresController: React.FC<PremieresControllerProps> = ({ shows }) => {
    const [pageTitle, setPageTitle] = useState<string | null>(null);
    const [pageDescription, setPageDescription] = useState<string | null>(null);

    useEffect(() => {
        // Set page title and description
        setPageTitle("PREMIERES");
        setPageDescription("Brand new shows showing this month.");
    }, []);

    return (
        <div>
            <h1>{pageTitle}</h1>
            <p>{pageDescription}</p>
            <ul>
                {shows.map((show, index) => (
                    <li key={index}>
                        {/* Render show details here */}
                    </li>
                ))}
            </ul>
        </div>
    );
};

export default PremieresController;
