// angular/src/app/components/ViewController.component.ts
// Converted from src/sections/view/view.ctrl.js

import { Component, Input, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { ShowService } from '../../services/show.service';
import { PageValues } from '../../services/page.val';

@Component({
  selector: 'app-view-controller',
  templateUrl: './view.tpl.html',
  styleUrls: ['./view.css']
})
export class ViewControllerComponent implements OnInit {
  @Input() show!: any;

  constructor(
    private showService: ShowService,
    private route: ActivatedRoute,
    private pageValues: PageValues
  ) {}

  ngOnInit(): void {
    this.pageValues.title = "VIEW";
    this.pageValues.description = `Overview, seasons & info for '${this.show.original_name}'.`;

    this.show.cast = [];
    this.showService.getCast(this.show.id).then(response => {
      this.show.cast = response.cast;
    });
  }

  setBannerImage() {
    return {
      'background': 'url() no-repeat',
      'background-size': '100%',
      'background-position': '100% 0%'
    };
  }
}

// react/src/components/ViewController.tsx
import React, { useEffect, useState } from 'react';
import { useParams } from 'react-router-dom';
import { PageValues } from '../../services/page.val';
import { ShowService } from '../../services/show.fct';

interface ViewControllerProps {
    show: any;
}

const ViewController: React.FC<ViewControllerProps> = ({ show }) => {
    const [cast, setCast] = useState([]);
    const { id } = useParams<{ id: string }>();

    useEffect(() => {
        // Set page title and description
        PageValues.title = "VIEW";
        PageValues.description = `Overview, seasons & info for '${show.original_name}'.`;

        // Fetch cast information
        ShowService.getCast(id).then(response => {
            setCast(response.cast);
        });
    }, [id, show.original_name]);

    const setBannerImage = () => {
        return {
            background: 'url() no-repeat',
            backgroundSize: '100%',
            backgroundPosition: '100% 0%'
        };
    };

    return (
        <div>
            <h1>{PageValues.title}</h1>
            <p>{PageValues.description}</p>
            <div style={setBannerImage()}></div>
            <div>
                {cast.map((member: any) => (
                    <div key={member.id}>
                        <p>{member.name}</p>
                    </div>
                ))}
            </div>
        </div>
    );
};

export default ViewController;
