// angular/src/app/components/show.component.ts
// Converted from src/components/show/show.drct.js

import { Component, Input, OnInit } from '@angular/core';
import { ShowService } from '../services/ShowService.service';

@Component({
  selector: 'app-show',
  templateUrl: './show.tpl.html',
  styleUrls: ['./show.css']
})
export default class ShowComponent implements OnInit {
  @Input() show!: any;
  genres: any[] = [];

  constructor(private showService: ShowService) {}

  ngOnInit(): void {
    this.showService.get(this.show.id).then(response => {
      this.genres = response.genres;
    });
  }
}

// react/src/components/directives/show.tsx
﻿// Converted from src/components/show/show.drct.js

import React, { useEffect, useState } from 'react';
import ShowService from '../../services/showService';

type ShowProps = {
    show: {
        id: number;
    };
};

const Show: React.FC<ShowProps> = ({ show }) => {
    const [genres, setGenres] = useState<string[]>([]);

    useEffect(() => {
        if (show.id) {
            ShowService.get(show.id).then((response) => {
                setGenres(response.genres);
            });
        }
    }, [show.id]);

    return (
        <div>
            <h2>Genres</h2>
            <ul>
                {genres.map((genre, index) => (
                    <li key={index}>{genre}</li>
                ))}
            </ul>
        </div>
    );
};

export default Show;
